### ISSUE TITLE
convert scripts

### ISSUE THREAD

**Issue by jac578** [phantrdat/onnx-efficientdet#1]
Hi,phantrdat, can you share the convert scripts from pytorch  model to onnx model.

**Comment by phantrdat** [comment]
Hi @jac578,

I have modified some code in the original repo for conversion purposes. Can I give you the full modified code via email?

**Comment by jac578** [comment]
> Hi @jac578,
> 
> I have modified some code in the original repo for conversion purposes. Can I give you the full modified code via email?

Of course. shi19871987@sina.com. Many thanks.

**Comment by joe807191330** [comment]
> > Hi @jac578,
> > I have modified some code in the original repo for conversion purposes. Can I give you the full modified code via email?
> 
> Of course. [shi19871987@sina.com](mailto:shi19871987@sina.com). Many thanks.

Hi,phantrdat,I also need this script file. Could you upload the relevant code? Or send me the file by email (807191330@qq.com). Thanks a lot.

**Comment by phantrdat** [comment]
@joe807191330 Please check your email.

**Comment by andrewwang0612** [comment]
Hi,phantrdat,
Sorry about that ,I also need this script file.
Could you send me the file by email to :andrewwang.aw1999@gmail.com
Thanks a lot!!

**Comment by dnns92** [comment]
Dear @phantrdat,
can you send me the modifications as well? huegledennis[at]gmail.com
